#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
#    username: root
#    password: root
#
#
##jpa settings
#
#jpa.hibernate.ddl_auto: create

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update   # Use `update` to avoid recreating the schema on each run; use `create` only if you want to reset data.
    show-sql: true       # Optional: enables SQL query logging in the console for debugging.
